const TourList = [
    {
        packageId: 1,
        travelType: "Culinary",
        imageUrl: "https://i1-dulich.vnecdn.net/2022/02/20/cho-200-03-6486-1645334322.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=uDMTTlAo4xI9NPUujCCW2w", 
        description: "Indulge in the culinary wonders of District 4, Ho Chi Minh City, on our immersive 4-hour food tour. Explore the vibrant streets and alleyways of this bustling district, guided by a local food enthusiast. Sample an array of delectable dishes, from savory street food to authentic Vietnamese delicacies. Savor the rich flavors and discover the unique blend of traditions that make District 4 a food lover's paradise. Join us for an unforgettable gastronomic adventure, where every bite tells a story of this dynamic and culturally rich neighborhood.", 
        name:"Street food tour in District 4", 
        duration: 4, 
        price: 20, 
        rating: 5,
        numberOfRating: 484,
        startDate: new Date("2023-08-23"),
        endDate: new Date("2023-08-27"),
    },
    {
        packageId: 1,
        travelType: "Culinary",
        imageUrl: "https://i1-dulich.vnecdn.net/2022/02/20/cho-200-03-6486-1645334322.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=uDMTTlAo4xI9NPUujCCW2w", 
        description: "Indulge in the culinary wonders of District 4, Ho Chi Minh City, on our immersive 4-hour food tour. Explore the vibrant streets and alleyways of this bustling district, guided by a local food enthusiast. Sample an array of delectable dishes, from savory street food to authentic Vietnamese delicacies. Savor the rich flavors and discover the unique blend of traditions that make District 4 a food lover's paradise. Join us for an unforgettable gastronomic adventure, where every bite tells a story of this dynamic and culturally rich neighborhood.", 
        name:"Street food tour in District 4", 
        duration: 4, 
        price: 20, 
        rating: 5,
        numberOfRating: 484,
        startDate: new Date("2023-08-23"),
        endDate: new Date("2023-08-27"),
    },
    {
        packageId: 1,
        travelType: "Culinary",
        imageUrl: "https://i1-dulich.vnecdn.net/2022/02/20/cho-200-03-6486-1645334322.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=uDMTTlAo4xI9NPUujCCW2w", 
        description: "Indulge in the culinary wonders of District 4, Ho Chi Minh City, on our immersive 4-hour food tour. Explore the vibrant streets and alleyways of this bustling district, guided by a local food enthusiast. Sample an array of delectable dishes, from savory street food to authentic Vietnamese delicacies. Savor the rich flavors and discover the unique blend of traditions that make District 4 a food lover's paradise. Join us for an unforgettable gastronomic adventure, where every bite tells a story of this dynamic and culturally rich neighborhood.", 
        name:"Street food tour in District 4", 
        duration: 4, 
        price: 20, 
        rating: 5,
        numberOfRating: 484,
        startDate: new Date("2023-08-23"),
        endDate: new Date("2023-08-27"),
    },
    {
        packageId: 1,
        travelType: "Culinary",
        imageUrl: "https://i1-dulich.vnecdn.net/2022/02/20/cho-200-03-6486-1645334322.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=uDMTTlAo4xI9NPUujCCW2w", 
        description: "Indulge in the culinary wonders of District 4, Ho Chi Minh City, on our immersive 4-hour food tour. Explore the vibrant streets and alleyways of this bustling district, guided by a local food enthusiast. Sample an array of delectable dishes, from savory street food to authentic Vietnamese delicacies. Savor the rich flavors and discover the unique blend of traditions that make District 4 a food lover's paradise. Join us for an unforgettable gastronomic adventure, where every bite tells a story of this dynamic and culturally rich neighborhood.", 
        name:"Street food tour in District 4", 
        duration: 4, 
        price: 20, 
        rating: 5,
        numberOfRating: 484,
        startDate: new Date("2023-08-23"),
        endDate: new Date("2023-08-27"),
    },
    {
        packageId: 1,
        travelType: "Culinary",
        imageUrl: "https://i1-dulich.vnecdn.net/2022/02/20/cho-200-03-6486-1645334322.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=uDMTTlAo4xI9NPUujCCW2w", 
        description: "Indulge in the culinary wonders of District 4, Ho Chi Minh City, on our immersive 4-hour food tour. Explore the vibrant streets and alleyways of this bustling district, guided by a local food enthusiast. Sample an array of delectable dishes, from savory street food to authentic Vietnamese delicacies. Savor the rich flavors and discover the unique blend of traditions that make District 4 a food lover's paradise. Join us for an unforgettable gastronomic adventure, where every bite tells a story of this dynamic and culturally rich neighborhood.", 
        name:"Street food tour in District 4", 
        duration: 4, 
        price: 20, 
        rating: 5,
        numberOfRating: 484,
        startDate: new Date("2023-08-23"),
        endDate: new Date("2023-08-27"),
    }
]

export default TourList