export const TourList = [
    {
        packageId: 1,
        travelType: "Culinary",
        imageUrl: "https://i1-dulich.vnecdn.net/2022/02/20/cho-200-03-6486-1645334322.jpg?w=1020&h=0&q=100&dpr=1&fit=crop&s=uDMTTlAo4xI9NPUujCCW2w", 
        description: "Indulge in the culinary wonders of District 4, Ho Chi Minh City, on our immersive 4-hour food tour. Explore the vibrant streets and alleyways of this bustling district, guided by a local food enthusiast. Sample an array of delectable dishes, from savory street food to authentic Vietnamese delicacies. Savor the rich flavors and discover the unique blend of traditions that make District 4 a food lover's paradise. Join us for an unforgettable gastronomic adventure, where every bite tells a story of this dynamic and culturally rich neighborhood.", 
        name:"Street food tour in District 4", 
        duration: 4, 
        price: 20, 
        rating: 5,
        numberOfRating: 484,
        startDate: new Date("2023-10-23"),
        endDate: new Date("2023-10-27"),
        tourguideId: 1,
        city: "Ho Chi Minh"
    },
    {
        "packageId": 16,
        "travelType": "Adventure",
        "imageUrl": "https://suckhoelamdep.vn/wp-content/uploads/2021/02/C%C3%81-scaled-1.jpeg",
        "description": "Embark on an exciting sea fishing adventure in the pristine waters off the coast of Vietnam. Our full-day trip offers you the opportunity to experience the thrill of catching your own seafood. We'll take you to the best fishing spots, provide the equipment you need, and guide you through the art of fishing. Cast your line into the sparkling waters, and enjoy the tranquility of the sea. As we explore the bountiful ocean, you'll have a chance to catch various fish species, and our expert guides will teach you the basics of fishing. Plus, you can savor your freshly caught fish in a delicious seaside barbecue. Join us for an unforgettable day of sea fishing and make memories that will last a lifetime.",
        "name": "Sea Fishing in One Day",
        "duration": 8,
        "price": 60,
        "rating": 4,
        numberOfRating: 234,
        "startDate": new Date("2023-11-12"),
        "endDate": new Date("2023-11-15"),
        tourguideId: 2,
        city: "Long An"
    },
    {
        "packageId": 15,
        "travelType": "Active",
        "imageUrl": "https://statics.vinpearl.com/vuon-quoc-gia-Bach-Ma-Hue-01_1690370773.jpg",
        "description": "Embark on an exhilarating hiking adventure in the stunning Bach Ma National Park. This full-day journey will lead you through lush forests, cascading waterfalls, and awe-inspiring landscapes. Our experienced guides will take you to the heart of this natural wonder, where you can explore the rich biodiversity and enjoy breathtaking vistas. Discover the hidden gems of Bach Ma, learn about the flora and fauna, and immerse yourself in the tranquil beauty of the park. This hiking experience is perfect for nature enthusiasts, adventure seekers, and those looking to connect with the great outdoors. Join us for an unforgettable day of exploration in Bach Ma National Park.",
        "name": "Bach Ma Hiking",
        "duration": 8,
        "price": 50,
        "rating": 3,
        numberOfRating: 100,
        "startDate": new Date("2023-11-01"),
        "endDate": new Date("2023-11-02"),
        tourguideId: 2,
        city: "Hue"
    },
    {
        packageId: 8,
        travelType: "Cultural",
        imageUrl: "https://aseanvietnam.vn/uploads/images/image_750x_62d5596b61730.jpg",
        description: "Step into the shoes of a local farmer for a day and discover the authentic rural life of our region. This immersive experience takes you to the heart of the countryside, where you'll engage in hands-on farming activities, from tilling the soil to planting crops. Work alongside local farmers, learn their time-honored techniques, and gain a profound appreciation for their way of life. Enjoy a farm-fresh meal with ingredients you've harvested yourself, and savor the fruits of your labor. Join me on this unforgettable journey, and let's embrace the simplicity and beauty of farming.",
        name: "A Day Living as a Farmer",
        duration: 7,
        price: 60,
        rating: 4,
        numberOfRating: 120,
        startDate: new Date("2023-11-01"),
        endDate: new Date("2023-11-01"),
        tourguideId: 3,
        city: "Moc Chau"
    },
    {
        "packageId": 11,
        "travelType": "Cultural",
        "imageUrl": "https://kyuchoian.com/userfiles/image/tour/hoi-an/2020/bo-anh-dep-hoi-an/pho-co/tren-cao/hoi-an-tren-cao-1.jpg",
        "description": "Immerse yourself in the culture of Hoi An. Visit places that only the locals know. A perfect way to experience the essence of this historic town.",
        "name": "Hidden gem wandering in Hoi An",
        "duration": 3,
        "price": 30,
        "rating": 5,
        numberOfRating: 213,
        "startDate": new Date("2023-10-20"),
        "endDate": new Date("2023-10-22"),
        tourguideId: 4,
        city: "Quang Nam"
    },
    {
        "packageId": 12,
        "travelType": "Culinary",
        "imageUrl": "https://centralvietnamguide.com/wp-content/uploads/2022/05/hoi-an-food-specialties-1.jpg",
        "description": "Savor the flavors of Hoi An's renowned dishes. Join me on a culinary adventure to discover the secrets of local cuisine right at my home. Taste authentic Vietnamese food at its best.",
        "name": "Learn how to cook from my mom",
        "duration": 4,
        "price": 35,
        "rating": 4,
        "numberOfRating": 128,
        "startDate": new Date("2023-16-10"),
        "endDate": new Date("2023-17-10"),
        tourguideId: 4,
        city: "Quang Nam"
    },
    {
        packageId: 3,
        travelType: "Culinary",
        imageUrl: "https://ik.imagekit.io/tvlk/blog/2022/08/dac-san-mien-tay-nam-bo-8.jpeg",
        description: "Experience the heartwarming flavors of Vietnam's Western cuisine with our delightful food tour. Over the course of 5 hours, you'll visit local homes and small eateries, sampling homemade dishes that have been cherished for generations. From savory pho to mouthwatering spring rolls, savor the authentic tastes that make this region's food special. Let our expert guides introduce you to the stories and traditions behind each dish, making this a culinary journey you won't forget.",
        name: "Homemade Food Tour in Vietnam Western",
        duration: 5,
        price: 30,
        rating: 4,
        numberOfRating: 128,
        startDate: new Date("2023-28-10"),
        endDate: new Date("2023-30-10"),
        tourguideId: 4,
        city: "Long An"
    },
    {
        packageId: 7,
        travelType: "Historical",
        imageUrl: "https://www.originvietnam.com/wp-content/uploads/IMG_01230363.jpg",
        description: "Embark on an enriching journey through the rich history and culture of Ho Chi Minh City with our 'Museums Tour.' This full-day experience will take you to some of the city's most iconic museums, allowing you to explore the past and present of this vibrant metropolis. Delve into the stories of Vietnam's struggle for independence, its diverse heritage, and contemporary art. Join me as your guide, and let's unravel the treasures and knowledge these museums have to offer, making your visit to Ho Chi Minh City an educational and memorable one.",
        name: "Museums Tour in Ho Chi Minh City",
        duration: 6,
        price: 45,
        rating: 5,
        numberOfRating: 29,
        startDate: new Date("2023-25-10"),
        endDate: new Date("2023-28-10"),
        tourguideId: 5,
        city: "Ho Chi Minh"
    },
    {
        packageId: 6,
        travelType: "Adventure",
        imageUrl: "https://dulichtaybac.vn/wp-content/uploads/2018/05/3.-H%C3%A1i-m%E1%BA%ADn-tam-hoa-Tu%E1%BA%A5n-L%E1%BB%A3i-1-750x437.jpg",
        description: "Embark on an exciting adventure with me as we journey into the heart of plum country. During this one-day trip, you'll have the unique opportunity to participate in plum harvesting, a tradition deeply rooted in our region. Pick plump, juicy plums from local orchards, learn the art of harvesting, and relish the flavors of freshly picked fruits. As we explore the picturesque landscapes and enjoy the tranquil countryside, you'll experience the authentic charm of plum harvesting, all guided by me.",
        name: "Plum Harvesting Adventure",
        duration: 8,
        price: 40,
        rating: 4,
        numberOfRating: 189,
        startDate: new Date("2023-01-11"),
        endDate: new Date("2023-03-11"),
        tourguideId: 5,
        city: "Moc Chau"
    },
    {
        packageId: 2,
        travelType: "Adventure",
        imageUrl: "https://vcdn-dulich.vnecdn.net/2021/10/11/13-8289-1633929177-3050-1633929368.jpg",
        description: "Embark on an exhilarating adventure as you trek to the breathtaking Nui Chua Mountain. This 6-hour journey takes you through lush forests and scenic trails, offering panoramic views of the Vietnamese landscape. Led by experienced guides, you'll not only conquer the peak but also learn about the local flora and fauna. Immerse yourself in the natural beauty of Nui Chua and make unforgettable memories along the way.",
        name: "Ba Vi Mountain Trek",
        duration: 6,
        price: 40,
        rating: 4,
        startDate: new Date("2023-11-03"),
        endDate: new Date("2023-11-10"),
        tourguideId: 1,
        city: "Ha Noi"
    }
]

export const TourGuideList = [
    {
        tourguideId: 1,
        name: "Nhiep Bao Chau",
        avatar: "https://bizweb.dktcdn.net/100/438/408/files/anh-chan-dung-dep-yodyvn1.jpg?v=1683537734987",
        language: "Vietnamese, English, Chinese",
        description: "Hello, I'm Chau, your personal tour guide living in the vibrant heart of Ho Chi Minh City. As a resident of this bustling metropolis, I'm deeply connected to its history, culture, and hidden treasures. I'm thrilled to be your companion on this journey through our incredible city. Whether you're passionate about history, eager to savor street food delights, or interested in off-the-beaten-path adventures, I'm here to craft a unique experience just for you. Together, we'll explore the stories that make this city come alive. Join me, and let's embark on an unforgettable adventure through the captivating streets of Ho Chi Minh City and the nearby.",
        hobby: ["Dogs lover", "Caring", "Trekking"],
        rating: 5,
        numberOfRating: 484,
    },
    {
        tourguideId: 2,
        name: "Linh Pham",
        avatar: "https://studiovietnam.com/wp-content/uploads/2021/07/chup-anh-chan-dung-troi-nang-6.jpg",
        language: "Vietnamese, English",
        description: "Xin chào! I'm Linh, your personal tour guide in the picturesque landscapes of Lao Cai. With deep roots in this region, I'm excited to accompany you on a journey through the beauty and culture of Lao Cai. Whether you're an adventure enthusiast, nature lover, or cultural explorer, I'm here to create a tailored experience just for you. Join me as we unravel the secrets of Lao Cai's serene charm, vibrant traditions, and lush natural surroundings.",
        hobby: ["Pets lover", "Photography", "Traditional music", "Gardening"],
        rating: 4,
        numberOfRating: 84,
    },
    {
        tourguideId: 3,
        name: "Trang Nguyen",
        avatar: "https://media.viez.vn/prod/2021/7/18/large_127135028_1216247922161274_8225139171053607991_n_9293e0e89b.jpg",
        language: "Vietnamese, English",
        description: "Chào bạn! I'm Trang, your dedicated tour guide in the serene province of Long An. Long An is not just my home; it's my passion. I'm eager to share the province's natural beauty and rich culture with you. Whether you're interested in exploring the lush landscapes, immersing yourself in local traditions, or discovering the tranquil way of life in Long An, I'm here to curate a personalized journey that suits your interests. Join me, and let's uncover the peaceful charms and hidden wonders of Long An together.",
        hobby: ["Cycling", "Bird-watching", "Traditional crafts", "Local cuisine"],
        rating: 3,
        numberOfRating: 200,
    }, 
    {
        tourguideId: 4,
        name: "Minh",
        avatar: "https://2sao.vietnamnetjsc.vn/images/2022/09/03/14/16/tinh-duc-2.jpg",
        language: "Vietnamese, English",
        description: "Hi, I'm Minh, your local guide in the charming city of Hoi An. I have a deep appreciation for the history and culture of this beautiful town. Let me take you on a journey through the narrow streets, ancient architecture, and vibrant markets of Hoi An. Whether you're interested in the local cuisine, historical sites, or simply exploring the picturesque surroundings, I'm here to make your visit unforgettable.",
        hobby: ["Photography", "Cycling", "Traditional crafts"],   
        rating: 5,
        numberOfRating: 189,
    },
    {
        tourguideId: 5,
        name: "Hung",
        avatar: "https://media.istockphoto.com/id/513474980/vi/anh/ch%C3%A2n-dung-ng%C6%B0%E1%BB%9Di-%C4%91%C3%A0n-%C3%B4ng-ch%C3%A2u-%C3%A1-%C4%91%E1%BA%B9p-trai-nh%E1%BA%A5t.jpg?s=612x612&w=0&k=20&c=zDHVqWI36wWiHskvh70KcjtePBE2pKUwpa49rjIsa3Y=",
        language: "Vietnamese, English",
        description: "Greetings! I'm Hung, your personal guide in the stunning city of Da Nang. With a passion for adventure and exploration, I'm here to show you the natural beauty, cultural richness, and vibrant life of Da Nang. Whether you're interested in hiking, beach relaxation, or exploring ancient temples, I'll tailor an experience that suits your preferences and ensures you have a memorable time in this wonderful city.",
        hobby: ["Hiking", "Beach Volleyball", "Painting"],   
        rating: 3,
        numberOfRating: 19,
    }
]